import Head from 'next/head'

import GpuListings from '../components/gpu-listings/GpuListings'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wen GPU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GpuListings />
    </div>
  )
}
